version: '2.1'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rome
    ports:
      - '5433:5432'
    volumes:
     - ./data/rome_u_journeys.csv:/docker-entrypoint-initdb.d/rome_u_journeys.csv

  scheduler:
    container_name: airflow-scheduler
    image: apache/airflow
    restart: always
    depends_on:
      - postgres
      - webserver
    env_file:
      - ./airflow/.env
    ports:
      - '8793:8793'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    command: scheduler
    healthcheck:
      test: ['CMD-SHELL', '[ -f /usr/local/airflow/airflow-webserver.pid ]']
      interval: 30s
      timeout: 30s
      retries: 3

  webserver:
    container_name: airflow-webserver
    image: apache/airflow
    hostname: webserver
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./airflow/.env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/scripts:/opt/airflow/scripts
      - ./airflow/logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    ports:
      - '8080:8080'
    entrypoint: ./scripts/airflow-entrypoint.sh
    command: bash -c "airflow users create --username admin --firstname Jack --lastname Sparrow --role Admin --email example@mail.org --password pass && airflow scheduler"
    healthcheck:
      test: ['CMD-SHELL', '[ -f /usr/local/airflow/airflow-webserver.pid ]']
      interval: 30s
      timeout: 30s
      retries: 32

  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "password"
    depends_on:
    - postgres

